Import('*')

INC = [ '#/vm/inc', '/usr/local/include/SDL2' ]

LIBS = [ 'libminiat', 'SDL2' ]

buildProgram("miniat_edisonJr", ["edisonJr.c", "led_block.c", "sevseg_display.c", "button_block.c", "SDL/edison_led.c", "SDL/edison_sdl.c", "SDL/edison_seven_segment.c", "SDL/edison_button.c", "SDL/edison_led_matrix.c", "SDL/edison_dipswitch.c"], CPPPATH=INC, LIBS=LIBS)
buildMash('assembly.asm')
